/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as ManifiestoRouteImport } from './routes/manifiesto'
import { Route as ManifestacionRouteImport } from './routes/manifestacion'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ArtistasRouteImport } from './routes/artistas'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ActualidadRouteImport } from './routes/actualidad'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifiestoRoute = ManifiestoRouteImport.update({
  id: '/manifiesto',
  path: '/manifiesto',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestacionRoute = ManifestacionRouteImport.update({
  id: '/manifestacion',
  path: '/manifestacion',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistasRoute = ArtistasRouteImport.update({
  id: '/artistas',
  path: '/artistas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualidadRoute = ActualidadRouteImport.update({
  id: '/actualidad',
  path: '/actualidad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualidad': typeof ActualidadRoute
  '/agenda': typeof AgendaRoute
  '/artistas': typeof ArtistasRoute
  '/galeria': typeof GaleriaRoute
  '/manifestacion': typeof ManifestacionRoute
  '/manifiesto': typeof ManifiestoRoute
  '/mapa': typeof MapaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualidad': typeof ActualidadRoute
  '/agenda': typeof AgendaRoute
  '/artistas': typeof ArtistasRoute
  '/galeria': typeof GaleriaRoute
  '/manifestacion': typeof ManifestacionRoute
  '/manifiesto': typeof ManifiestoRoute
  '/mapa': typeof MapaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualidad': typeof ActualidadRoute
  '/agenda': typeof AgendaRoute
  '/artistas': typeof ArtistasRoute
  '/galeria': typeof GaleriaRoute
  '/manifestacion': typeof ManifestacionRoute
  '/manifiesto': typeof ManifiestoRoute
  '/mapa': typeof MapaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualidad'
    | '/agenda'
    | '/artistas'
    | '/galeria'
    | '/manifestacion'
    | '/manifiesto'
    | '/mapa'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualidad'
    | '/agenda'
    | '/artistas'
    | '/galeria'
    | '/manifestacion'
    | '/manifiesto'
    | '/mapa'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/actualidad'
    | '/agenda'
    | '/artistas'
    | '/galeria'
    | '/manifestacion'
    | '/manifiesto'
    | '/mapa'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualidadRoute: typeof ActualidadRoute
  AgendaRoute: typeof AgendaRoute
  ArtistasRoute: typeof ArtistasRoute
  GaleriaRoute: typeof GaleriaRoute
  ManifestacionRoute: typeof ManifestacionRoute
  ManifiestoRoute: typeof ManifiestoRoute
  MapaRoute: typeof MapaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifiesto': {
      id: '/manifiesto'
      path: '/manifiesto'
      fullPath: '/manifiesto'
      preLoaderRoute: typeof ManifiestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifestacion': {
      id: '/manifestacion'
      path: '/manifestacion'
      fullPath: '/manifestacion'
      preLoaderRoute: typeof ManifestacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistas': {
      id: '/artistas'
      path: '/artistas'
      fullPath: '/artistas'
      preLoaderRoute: typeof ArtistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualidad': {
      id: '/actualidad'
      path: '/actualidad'
      fullPath: '/actualidad'
      preLoaderRoute: typeof ActualidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualidadRoute: ActualidadRoute,
  AgendaRoute: AgendaRoute,
  ArtistasRoute: ArtistasRoute,
  GaleriaRoute: GaleriaRoute,
  ManifestacionRoute: ManifestacionRoute,
  ManifiestoRoute: ManifiestoRoute,
  MapaRoute: MapaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
